import type { Metadata } from "next";
import { Michroma } from "next/font/google";
import "./globals.css";
import ContextWrapper from "./context/context";
import { ReactNode } from "react";

const michroma = Michroma({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: ReactNode;
  modal: ReactNode;
}) {
  return (
    <html lang="en">
      <body className={michroma.className}>
        <ContextWrapper>
          {children}
          {modal}
        </ContextWrapper>
      </body>
    </html>
  );
}
