import type { Metadata } from "next";
import { Michroma } from "next/font/google";
import "./globals.css";
import ContextWrapper from "./context/context";

const michroma = Michroma({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={michroma.className}>
        <ContextWrapper>{children}</ContextWrapper>
      </body>
    </html>
  );
}
